---
version: "2.1"
services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kyiv
      - URL=DOMAIN
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - CERTPROVIDER=zerossl #optional
      - DNSPLUGIN=cloudflare #optional
      #- DUCKDNSTOKEN=<token> #optional
      - EMAIL=EMAIL #optional
      #- ONLY_SUBDOMAINS=false #optional
      #- EXTRA_DOMAINS=<extradomains> #optional
      #- STAGING=false #optional
    volumes:
      - /home/pi/docker-configs/swag/config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
networks:
  default:
    external:
      name: container-local