version: "3.5"
services:
  scrutiny:
    #image: ghcr.io/linuxserver/scrutiny:8e34ef8d-ls35
    image: ghcr.io/analogj/scrutiny:master-omnibus
    container_name: scrutiny-pi
    privileged: true
    cap_add:
      - SYS_RAWIO
    volumes:
      #mount storage for config store
      - /data/scrutiny/config:/config
      - /run/udev:/run/udev:ro
      - /data/scrutiny/influxdb:/opt/scrutiny/influxdb
    ports:
      - "8020:8080" # web
      - "8086:8086" # influxDB
    devices:
      - "/dev/sda"
      - "/dev/sdb"
      - "/dev/sdc" # comment row if you don't have 3hird drive
    restart: unless-stopped